### ISSUE TITLE
Update to new Govee API

### ISSUE THREAD

**Issue by wiltodelta** [wiltodelta/homeassistant-govee-smart-heater-h7131#2]
https://developer.govee.com/reference/get-you-devices

**Comment by ilyasubkhankulov** [comment]
hey @wiltodelta I pushed PR #4 with the necessary changes. Could you please review?
I've successfully tested on Home Assistant version 2024.7.4

**Comment by wiltodelta** [comment]
Thank you for the contribution @ilyasubkhankulov!
